//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POD.Portal
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("POD.Portal.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account is disabled..
        /// </summary>
        public static string AccountDisabled {
            get {
                return ResourceManager.GetString("AccountDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account is inavtice. Please set password with the link sent to your email..
        /// </summary>
        public static string AccountInactive {
            get {
                return ResourceManager.GetString("AccountInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account has been locked. Please reset your password..
        /// </summary>
        public static string AccountLockout {
            get {
                return ResourceManager.GetString("AccountLockout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords don&apos;t match..
        /// </summary>
        public static string ConfirmPasswordMatch {
            get {
                return ResourceManager.GetString("ConfirmPasswordMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The customer has been successfully added. An email has been sent to the admin.
        /// </summary>
        public static string CustomerAddedSuccessfully {
            get {
                return ResourceManager.GetString("CustomerAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The customer has been successfully modified..
        /// </summary>
        public static string CustomerEditedSuccessfully {
            get {
                return ResourceManager.GetString("CustomerEditedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account name is required..
        /// </summary>
        public static string CustomerNameIsRequired {
            get {
                return ResourceManager.GetString("CustomerNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account number is required..
        /// </summary>
        public static string CustomerNumberIsRequired {
            get {
                return ResourceManager.GetString("CustomerNumberIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email to reset your password..
        /// </summary>
        public static string EmailCheckMessage {
            get {
                return ResourceManager.GetString("EmailCheckMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is required..
        /// </summary>
        public static string EmailFieldIsRequired {
            get {
                return ResourceManager.GetString("EmailFieldIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your account.
        /// </summary>
        public static string EmailTempConfirmEmailSubject {
            get {
                return ResourceManager.GetString("EmailTempConfirmEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset - Hope POD Customer Portal.
        /// </summary>
        public static string EmailTempForgotPasswordSubject {
            get {
                return ResourceManager.GetString("EmailTempForgotPasswordSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User details for Hope POD Customer Portal.
        /// </summary>
        public static string EmailTempSetPasswordSubject {
            get {
                return ResourceManager.GetString("EmailTempSetPasswordSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must contain one lower &amp; uppercase letter, a number and a symbol..
        /// </summary>
        public static string ErrorMessagePasswordContain {
            get {
                return ResourceManager.GetString("ErrorMessagePasswordContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be between 6 and 20 characters..
        /// </summary>
        public static string ErrorMessagePasswordLength {
            get {
                return ResourceManager.GetString("ErrorMessagePasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgotten password.
        /// </summary>
        public static string ForgottenPassword {
            get {
                return ResourceManager.GetString("ForgottenPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name is required..
        /// </summary>
        public static string FullNameIsRequired {
            get {
                return ResourceManager.GetString("FullNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name or password is incorrect.
        /// </summary>
        public static string InncorectCredentials {
            get {
                return ResourceManager.GetString("InncorectCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is not valid..
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Password field is required..
        /// </summary>
        public static string PasswordFieldIsRequired {
            get {
                return ResourceManager.GetString("PasswordFieldIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has been successfully set.  Please login &lt;a href=&quot;/Account/Login&quot;&gt;here &lt;/a&gt;.
        /// </summary>
        public static string ResetPasswordSuccess {
            get {
                return ResourceManager.GetString("ResetPasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Level is required..
        /// </summary>
        public static string RoleNameIsRequired {
            get {
                return ResourceManager.GetString("RoleNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status is required..
        /// </summary>
        public static string StatusNameIsRequired {
            get {
                return ResourceManager.GetString("StatusNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        public static string ThePasswordAndConfirmationPasswordDoNotMatch {
            get {
                return ResourceManager.GetString("ThePasswordAndConfirmationPasswordDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user has been successfully added. An email has been sent..
        /// </summary>
        public static string UserAddedSuccessfully {
            get {
                return ResourceManager.GetString("UserAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user has been successfully deleted..
        /// </summary>
        public static string UserDeletedSuccessfully {
            get {
                return ResourceManager.GetString("UserDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user has been successfully modified..
        /// </summary>
        public static string UserEditedSuccessfully {
            get {
                return ResourceManager.GetString("UserEditedSuccessfully", resourceCulture);
            }
        }
    }
}
